version: '3.8'

services:
  app:
    container_name: ionic-notes-app
    build: .
    ports:
      - '8100:8100'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
