import { addIcons } from 'ionicons';
import {
  gridOutline,
  todayOutline,
  folderOutline,
  settingsOutline,
  logOutOutline,
  eyeOutline,
  eyeOffOutline,
  menuOutline,
  timeOutline,
  pricetagOutline,
  fitnessOutline,
  addCircleOutline,
  flagOutline,
  documentTextOutline,
  listOutline,
  checkmarkDoneOutline,
  heartOutline,
  flashOutline,
  star,
  starOutline,
  chevronBackOutline,
  albumsOutline,
  chevronForwardOutline,
  addOutline,
  folderOpenOutline,
  briefcaseOutline,
  personOutline,
  closeOutline,
  layersOutline,
  schoolOutline,
  checkmarkCircleOutline,
  homeOutline,
  calendarOutline,
  carOutline,
  checkmarkOutline,
  banOutline,
  trashOutline,
  refresh,
  createOutline,
} from 'ionicons/icons';

export function registerIcons() {
  addIcons({
    'grid-outline': gridOutline,
    'today-outline': todayOutline,
    'folder-outline': folderOutline,
    'settings-outline': settingsOutline,
    'log-out-outline': logOutOutline,
    'eye-outline': eyeOutline,
    'eye-off-outline': eyeOffOutline,
    'menu-outline': menuOutline,
    'time-outline': timeOutline,
    'pricetag-outline': pricetagOutline,
    'fitness-outline': fitnessOutline,
    'add-circle-outline': addCircleOutline,
    'flag-outline': flagOutline,
    'document-text-outline': documentTextOutline,
    'list-outline': listOutline,
    'checkmark-done-outline': checkmarkDoneOutline,
    'heart-outline': heartOutline,
    'flash-outline': flashOutline,
    star,
    'star-outline': starOutline,
    'pricetags-outline': pricetagOutline,
    'chevron-back-outline': chevronBackOutline,
    'albums-outline': albumsOutline,
    'chevron-forward-outline': chevronForwardOutline,
    'add-outline': addOutline,
    'folder-open-outline': folderOpenOutline,
    'briefcase-outline': briefcaseOutline,
    'person-outline': personOutline,
    'close-outline': closeOutline,
    'layers-outline': layersOutline,
    'school-outline': schoolOutline,
    'check-circle-outline': checkmarkCircleOutline,
    'home-outline': homeOutline,
    'calendar-outline': calendarOutline,
    'cart-outline': carOutline,
    'checkmark-outline': checkmarkOutline,
    'ban-outline': banOutline,
    'trash-outline': trashOutline,
    refresh: refresh,
    'create-outline': createOutline,
  });
}
